### ISSUE TITLE
Does taskwarrior diagnostics reflect pirate hooks as well?

### ISSUE THREAD

**Issue by kaushikgopal** [tbabej/taskwarrior-shift-all-recurrence-hook#11]
After upgrading to taskwarrior `2.6.0` and moving a couple of things around I noticed that this pirate hook was not being "registered" in the diagnostics page

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1042037/138340150-aa143b3d-10db-4d3e-9adb-1724fbfc2212.png">
<img width="613" alt="CleanShot 2021-10-21 at 11 59 54@2x" src="https://user-images.githubusercontent.com/1042037/138340180-cab80056-b26b-4bbd-92b8-731004472fa5.png">

Is it enabled, but just not reported? or could it be that the hook is actually not registered?

**Comment by tbabej** [comment]
The "pirate" hook will not show up in the `task diag`, because it is invisible to TW itself. Only the main entrypoints (`on-modify-pirate` and the `on-add-pirate`) will be visible to TW, and the pirate hooks are imported in the Python runtime of those two hook scripts dynamically. This helps with the performance if you have multiple hooks (because the libraries and Python runtime have to be setup only once), but the side effect, is - as you discovered - that the pirate hooks are invisible to TW :slightly_smiling_face:

**Comment by kaushikgopal** [comment]
Ahh thanks for the detailed  explanation. Helps me understand  the behavior now. 🙏🏽
