### ISSUE TITLE
What about the 'until' attribute?

### ISSUE THREAD

**Issue by jpotier** [tbabej/taskwarrior-shift-all-recurrence-hook#6]
> […] inherit wait, scheduled and until attributes from the parent.

I'm not familiar with the `tasklib` module, however I see no mention of the `until` attribute. Also, when I tested this hook earlier, it didn't shift the `until` attribute. Is this the expected behavior?

**Comment by tbabej** [comment]
I have vague impression that I removed it from the list because I thought taskwarrior implements shifting of the `until` attribute. However, given that #5 also exists, it might be the case that I botched it up and the `wait` attribute is the one being shifted by taskwarrior.

I have a lot on my hands right now, so if somebody could make a definitive statement (by testing it) about the TW behaviour, so that we know the list of attrs that we should shift, I'd very appreciate that. Then we could sort both #5 and #6 out.

**Comment by jpotier** [comment]
I'll be testing this in the following week.

**Comment by xeruf** [comment]
After a lot of experimentation I finally found a one-liner that can test this(on linux) without messing with your existing config:
```sh
TASKDATA=$(xdg-user-dir CACHE)/task-test TASKRC=$TASKDATA/taskrc sh -c 'mkdir -p $TASKDATA && yes | task config reccurence.limit 2 && task add test recur:1min due:5s wait:3s scheduled:4s until:2min && sleep 6 && task all && task 2 3'
```
The output should look something like this:
![image](https://user-images.githubusercontent.com/13354331/83075445-27a50c80-a074-11ea-8988-bbcce121a001.png)
As you can see, `due` and `wait` are shifted, while `scheduled` and `until` are not.
Using Taskwarrior 2.5.1

**Comment by sim590** [comment]
I'm not sure how I should interpret `until` in
```
task add test recur:1min due:30s wait:due-25s until:due+5s
```
Should I interpret that all tasks are going to be deleted after 35 seconds. In vanilla taskwarrior, anyway I guess so. But using the hook, I was under the impression that new tasks should be created each minute showing up 5 seconds after that (`recurtime+duetime-25s = recurtime+5s`) and be deleted every 1min35s (5s after the due time). But after that, after a whole minute, another task should start and the cycle should continue, no? Because, as of now, using the hook (if I'm using it right), it doesn't work. The above deletes all the tasks and no other tasks are created from the template after 35 seconds...

**Comment by fullstopslash** [comment]
I'm experiencing this same behavior.  the until: tag behavior for vanilla task warrior is still active, which makes the parent task get deleted when it reaches it's expiration date.
